
SELECT * FROM SYS.DATABASES

ALTER DATABASE PENSKE SET COMPATIBILITY_LEVEL = 90
GO
ALTER DATABASE PENSKE SET COMPATIBILITY_LEVEL = 80

SET STATISTICS TIME OFF

SELECT	--dbo.SqlConcat(NOTA_FISCAL),
	dbo.Concat(NOTA_FISCAL, ' / ')
FROM	(SELECT *
	 FROM NOTA_FISCAL
	 WHERE DOCTO_TRANSPORTE_ID IN (1273617, 1273699, 1273579, 2579199, 7738413) ) NF
GROUP BY DOCTO_TRANSPORTE_ID


SELECT	TOP 50 
	DT.num_docto_transporte,
	NOTA_FISCAL
FROM
	DOCTO_TRANSPORTE DT WITH(NOLOCK)
	CROSS APPLY (
	SELECT NOTA_FISCAL = dbo.Concat(NOTA_FISCAL, ' /')
	FROM NOTA_FISCAL NF WITH(NOLOCK)
	WHERE NF.DOCTO_TRANSPORTE_ID = DT.DOCTO_TRANSPORTE_ID
	) NF
WHERE
	DT.DOCTO_TRANSPORTE_ID IN (1273617, 1273699, 1273579, 2579199, 7738413)

SELECT	TOP 50 
	DT.NUM_DOCTO_TRANSPORTE,
	NOTA_FISCAL = (	SELECT dbo.Concat(NOTA_FISCAL + '-' + serie, ' / ')
			FROM NOTA_FISCAL NF WITH(NOLOCK)
			WHERE NF.DOCTO_TRANSPORTE_ID = DT.DOCTO_TRANSPORTE_ID)
FROM
	DOCTO_TRANSPORTE DT WITH(NOLOCK)
WHERE
	DT.DOCTO_TRANSPORTE_ID IN (1273617, 1273699, 1273579, 2579199, 7738413)



SELECT DOCTO_TRANSPORTE_ID, COUNT(*)-- dbo.SqlConcat(NOTA_FISCAL)
FROM NOTA_FISCAL
GROUP BY DOCTO_TRANSPORTE_ID
HAVING COUNT(*) > 3
ORDER BY 2 DESC