
SET ANSI_NULLS OFF
Print 'SET ANSI_NULLS OFF'

DECLARE @TESTE_INT INT
--SELECT @TESTE_INT
IF @TESTE_INT != 1
	PRINT 'true'
ELSE
	PRINT 'false'

SET ANSI_NULLS ON
Print 'SET ANSI_NULLS ON'

--SELECT @TESTE_INT
IF @TESTE_INT != 1 OR @TESTE_INT IS NULL
	PRINT 'true'
ELSE
	PRINT 'false'
GO
SET CONCAT_NULL_YIELDS_NULL OFF
Print 'SET CONCAT_NULL_YIELDS_NULL OFF'

DECLARE @TESTE_INT INT
--SELECT @TESTE_INT
IF @TESTE_INT != 1
	PRINT 'true'
ELSE
	PRINT 'false'

SET CONCAT_NULL_YIELDS_NULL ON
Print 'SET CONCAT_NULL_YIELDS_NULL ON'

--SELECT @TESTE_INT
IF @TESTE_INT != 1
	PRINT 'true'
ELSE
	PRINT 'false'