DROP PROC SP_TESTE_ERROR
DROP PROC SP_TESTE_ERROR_NESTED

CREATE PROC SP_TESTE_ERROR_NESTED
AS

	DECLARE @INT INT,
		@VAR VARCHAR(30),
		@MENSAGEM VARCHAR(3000)


	SET @INT = 'TESTE NESTED'

	
GO

ALTER PROC SP_TESTE_ERROR
AS
	DECLARE @INT INT,
		@VAR VARCHAR(30),
		@MENSAGEM VARCHAR(3000)

	EXEC ('EXEC SP_TESTE_ERROR_NESTED')
	
	BEGIN TRY
		SET @INT = 'TESTAMDP'
	END TRY
	BEGIN CATCH
		SET @MENSAGEM = 'Erro . ' + ISNULL(ERROR_PROCEDURE(),'') + ' - ' + ERROR_MESSAGE() + '. Linha: ' + CONVERT(VARCHAR, ERROR_LINE()) + '. '
		RAISERROR (@MENSAGEM, 16, 1)	
	END CATCH


GO

BEGIN TRY
	EXEC SP_TESTE_ERROR
END TRY
BEGIN CATCH
	
	SELECT ERROR_MESSAGE(), ERROR_LINE(), ERROR_PROCEDURE()

END CATCH