CREATE TABLE TESTE (ID INT NOT NULL IDENTITY PRIMARY KEY CLUSTERED, DESCR VARCHAR (30) NULL)
GO
--SELECT * FROM TESTE
BEGIN TRAN
INSERT TESTE
SELECT 'TESTE 1'
UNION
SELECT 'TESTE 2'
ROLLBACK

GO
ALTER TRIGGER TR_TESTE ON TESTE
INSTEAD OF INSERT
AS
	SELECT *, [@@IDENT] = @@IDENTITY, SCOPE = SCOPE_IDENTITY() FROM inserted

	INSERT TESTE
	SELECT DESCR
	FROM INSERTED
GO