DROP TABLE DOCTO_TR_TESTE
DROP TABLE DOCTO_TR_TESTE2
GO
CREATE TABLE DOCTO_TR_TESTE (ID INT NOT NULL IDENTITY PRIMARY KEY,
	DESCRICAO VARCHAR(50) NULL
)
GO
ALTER TRIGGER TR_DOCTO_TR_TESTE ON DOCTO_TR_TESTE
AFTER UPDATE
AS 
SELECT [TR 1] = TRIGGER_NESTLEVEL()
UPDATE DOCTO_TR_TESTE
SET DESCRICAO += ' ' + DESCRICAO
GO
INSERT DOCTO_TR_TESTE
VALUES('TESTE')
GO
UPDATE	DOCTO_TR_TESTE
SET	DESCRICAO = 'TESTE'
GO
SELECT * FROM DOCTO_TR_TESTE
GO
CREATE TABLE DOCTO_TR_TESTE2 (ID INT NOT NULL IDENTITY PRIMARY KEY,
	DESCRICAO VARCHAR(50) NULL
)
GO
ALTER TRIGGER TR_DOCTO_TR_TESTE2 ON DOCTO_TR_TESTE2
AFTER UPDATE
AS 
SELECT [TR 2] = TRIGGER_NESTLEVEL()
UPDATE DOCTO_TR_TESTE
SET DESCRICAO += ' ' + DESCRICAO


INSERT DOCTO_TR_TESTE2
VALUES('TESTE2')

SELECT * FROM DOCTO_TR_TESTE
SELECT * FROM DOCTO_TR_TESTE2
