BEGIN TRAN

UPDATE INFRA_IDS SET PESSOA_ID += 1
SELECT PESSOA_ID FROM INFRA_IDS WITH(READCOMMITTED)

ROLLBACK

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT PESSOA_ID FROM INFRA_IDS WITH(READCOMMITTED)