SELECT	TOP 50000 REGISTRO_ID = L.REGISTRO_ID, L.TABELA_SISTEMA_ID, LOG_SISTEMA_ID = MAX(L.LOG_SISTEMA_ID)
INTO #TESTE
FROM	LOG_SISTEMA L
GROUP BY L.REGISTRO_ID, L.TABELA_SISTEMA_ID


;WITH 
DDL_NEW AS (
	SELECT	OBJECTNAME, EVENTDATE = MIN(EVENTDATE)
	FROM	DDLEVENTS
	GROUP BY OBJECTNAME
),
DDL_OLD AS (
	SELECT	DO.*
	FROM	DDL_NEW DN
		OUTER APPLY(
		SELECT	TOP 1 OBJECTNAME, EVENTDATE
		FROM	DDLEVENTS DO
		WHERE	DN.OBJECTNAME = DO.OBJECTNAME
		AND	DN.EVENTDATE != DO.EVENTDATE
		ORDER BY DO.EVENTDATE ASC
		) DO
)

SELECT	* 
FROM	DDL_NEW
UNION
SELECT	*
FROM	DDL_OLD
ORDER BY 1, 2

--SELECT * FROM DDLEVENTS WHERE OBJECTNAME = 'SP_037_CON_CFOP21'
--SELECT * FROM DDLEVENTS WHERE OBJECTNAME = 'SP_037_CON_CFOP21'


--SP_SPACEUSED DDLEVENTS


--14.293.686

--EXEC sp_estimate_data_compression_savings
--@schema_name = 'dbo',
--@object_name = 'LOG_SISTEMA',
--@index_id = NULL,
--@partition_number = NULL,
--@data_compression = 'PAGE'

SP_HELPINDEX DDLEVENTS